### ISSUE TITLE
MNAR data generation

### ISSUE THREAD

**Issue by lbotti319** [lbotti319/bayesian_math_scores#3]
Lets say we want to remove data based on a numerical value, where the probability that it is missing goes up as the value does.

Set some constant `x`, and for each row with covariate value `a` sample from a uniform distribution u = U(0,a) and remove if x<u.

The covariates can be normalized, or the base distribution can be different from U(0,1) to make it more flexible and work with the data as needed.

```
def remove_decision(a):
    x = 0.3
    u = uniform(0,a)
    if x < u:
        return True
    return False

df['example'].apply(remove_decision)

```

**Comment by inespancorbo** [comment]
Yea I think this would satisfy a MNAR scenario. Say our explanatory variable which will have missing values Age. It can be as simple as just assuming P({Age=NA})=1 if age > 15 and 0 otherwise. Any missing mechanism that depends on the values that are missing would be MNAR -- at least that is how I understood haha!
